using System;

// Canonical input action ids used by the keybinding/input system.
// The numeric gaps appear intentional so actions can be grouped by feature:
// general commands, camera/time controls, inventory, PDA, flight, and quickbar.
public enum GameAction
{
	// Global/debug/menu controls.
	none,
	cmdDebug,
	cmdEscape,
	cmdAccept,
	cmdCancel,
	cmdMenu,
	cmdToggleToolTipDetail,
	cmdForce,
	cmdToggleFog = 11,
	cmdScreenshot,
	cmdConsole,
	cmdReload = 15,
	cmdSave,
	cmdToggleFilters = 18,
	cmdTemp1 = 21,
	cmdTemp2,
	cmdTemp3,
	cmdTemp4,
	cmdTemp5,
	cmdTemp6,
	cmdTemp7,
	cmdTemp8,
	cmdTemp0 = 20,
	// Camera, time, and selection controls.
	cmdPanCamUp = 30,
	cmdPanCamLeft,
	cmdPanCamDown,
	cmdPanCamRight,
	cmdCentrePlayer,
	cmdZoomIn,
	cmdZoomOut,
	cmdRotateCCW = 38,
	cmdRotateCW,
	cmdPause,
	cmdTimeFaster,
	cmdTimeSlower,
	cmdPanFaster = 48,
	cmdPanSlower,
	cmdInventory,
	cmdRotateItem,
	cmdQuickMove,
	cmdSingleItem,
	cmdEyedropper,
	// PDA and ship flight controls.
	cmdPDAToggle = 60,
	cmdPDAHome,
	cmdPDA1,
	cmdPDA2,
	cmdPDA3,
	cmdPDA4,
	cmdPDA5,
	cmdClosePDA = 69,
	cmdFlyUp,
	cmdFlyDown,
	cmdFlyLeft,
	cmdFlyRight,
	cmdRotateShipCW,
	cmdRotateShipCCW,
	cmdAttitude,
	cmdLockW,
	cmdMatchSpeed,
	cmdToggleRCS = 80,
	cmdToggleShipNames,
	cmdToggleTracking,
	cmdToggleFocus,
	cmdClearTrack,
	cmdClearProx,
	cmdPrintStatus = 88,
	cmdShipLogs,
	cmdTogglePowerVis,
	cmdToggleDamage,
	cmdToggleZoneUI,
	cmdToggleGasVis,
	cmdZoneAlternate,
	cmdCycleCrew = 100,
	// UI panel and quick action bindings.
	cmdUIPanelBottom = 110,
	cmdUIPanelLeft,
	cmdUIPanelRight,
	cmdUIPanelTop,
	cmdQuickAction1 = 120,
	cmdQuickAction2,
	cmdQuickAction3,
	cmdQuickAction4,
	cmdQuickActionExpand,
	cmdQuickActionReset,
	cmdQuickActionPin,
	cmdLAlt = 128,
	cmdNudgeSelUp = 130,
	cmdNudgeSelLeft,
	cmdNudgeSelDown,
	cmdNudgeSelRight
}
